version: '3'

tasks:
  test:
    desc: Run unit tests
    cmds:
      - go test -v ./...
    env:
      GOFLAGS: -count=1
      CGO_ENABLED: 0
  test-race:
    desc: Run unit tests with -race flag
    cmds:
      - go test -v -race ./...
    env:
      GOFLAGS: -count=1
      CGO_ENABLED: 1
  lint:
    desc: Run linter
    cmds:
      - golangci-lint run -v ./... --fix
  verify:
    desc: Run linter and unit tests together
    deps:
      - test
      - lint
  vendor:
    desc: Update vendor dependencies
    cmds:
      - go mod tidy
      - go mod vendor
